/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TopicTopicIdImport } from './routes/topic/$topicId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TopicTopicIdRoute = TopicTopicIdImport.update({
  id: '/topic/$topicId',
  path: '/topic/$topicId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/topic/$topicId': {
      id: '/topic/$topicId'
      path: '/topic/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof TopicTopicIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/topic/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/topic/$topicId'
  id: '__root__' | '/' | '/topic/$topicId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TopicTopicIdRoute: typeof TopicTopicIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TopicTopicIdRoute: TopicTopicIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/topic/$topicId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/topic/$topicId": {
      "filePath": "topic/$topicId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
